import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';
import { getCatalogEditor } from '../../catalog-access';
import { z } from 'zod';
const url = z.string().max(2000).refine(s => !s || /^https?:\/\//i.test(s) && (() => {try {new URL(s); return true;} catch{return false;}})());
const record = z.object({id:z.string().max(100).optional(),name:z.string().trim().min(1).max(120),type:z.enum(['skill','mcp']),category:z.string().max(100),description:z.string().trim().min(1).max(500),details:z.string().max(20000),tags:z.string().max(500),github:url,website:url,image:z.string().max(2000).refine(s=>!s||s.startsWith('/api/images/')||url.safeParse(s).success),installation:z.string().max(10000)});
function db(){if(!env.DB)throw Error('Database unavailable');return env.DB;}
async function run(req:Request, action:(owner:string)=>Promise<Response>){try{const user=await getChatGPTUser();if(!user)return Response.json({error:'Войдите в аккаунт, чтобы открыть библиотеку.'},{status:401});if(!await getCatalogEditor())return Response.json({error:'Управление доступно только владельцу каталога.'},{status:403});if(req.method!=='GET'){const origin=req.headers.get('origin');if(origin && origin!==new URL(req.url).origin)return Response.json({error:'Недопустимый источник запроса'},{status:403});}return await action(user.userId);}catch(e){console.error(e);return Response.json({error:'Не удалось связаться с хранилищем. Попробуйте ещё раз.'},{status:500});}}
export async function GET(req:Request){try{const [items,cats,editor]=await Promise.all([db().prepare('SELECT id,name,type,category,description,details,tags,github,website,image,installation,created,updated FROM entries ORDER BY created DESC').all(),db().prepare('SELECT id,name FROM categories ORDER BY name').all(),getCatalogEditor()]);return Response.json({items:items.results,categories:cats.results,canEdit:!!editor},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:'Не удалось загрузить каталог. Попробуйте ещё раз.'},{status:503});}}
export async function POST(req:Request){return write(req,false);}
export async function PUT(req:Request){return write(req,true);}
async function write(req:Request,update:boolean){return run(req,async owner=>{let body:any;try{body=await req.json();}catch{return Response.json({error:'Некорректные данные'},{status:400});}if(body.entity==='category'){const name=typeof body.name==='string'?body.name.trim():'';if(!name||name.length>80)return Response.json({error:'Название категории: от 1 до 80 символов.'},{status:400});const same=await db().prepare('SELECT id FROM categories WHERE owner = ? AND lower(name) = lower(?) AND id != ?').bind(owner,name,update?body.id:'').first();if(same)return Response.json({error:'Такая категория уже есть.'},{status:409});const id=update?body.id:crypto.randomUUID();if(update)await db().prepare('UPDATE categories SET name = ? WHERE id = ? AND owner = ?').bind(name,id,owner).run();else await db().prepare('INSERT INTO categories (id,owner,name) VALUES (?,?,?)').bind(id,owner,name).run();return Response.json({id});}const parsed=record.safeParse(body);if(!parsed.success)return Response.json({error:'Проверьте название, описание и ссылки.'},{status:400});const p=parsed.data;if(p.category&&!await db().prepare('SELECT id FROM categories WHERE id = ? AND owner = ?').bind(p.category,owner).first())return Response.json({error:'Категория не найдена.'},{status:400});const now=new Date().toISOString();const fields=[p.name,p.type,p.category,p.description,p.details,p.tags,p.github,p.website,p.image,p.installation];if(update){if(!p.id)return Response.json({error:'Запись не найдена'},{status:400});const result=await db().prepare('UPDATE entries SET name=?,type=?,category=?,description=?,details=?,tags=?,github=?,website=?,image=?,installation=?,updated=? WHERE id=? AND owner=?').bind(...fields,now,p.id,owner).run();if(!result.meta.changes)return Response.json({error:'Запись не найдена'},{status:404});}else await db().prepare('INSERT INTO entries (name,type,category,description,details,tags,github,website,image,installation,updated,id,owner,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(...fields,now,crypto.randomUUID(),owner,now).run();return Response.json({ok:true});});}
export async function DELETE(req:Request){return run(req,async owner=>{const p=new URL(req.url).searchParams;const id=p.get('id');if(!id)return Response.json({error:'Не указана запись'},{status:400});if(p.get('entity')==='category')await db().batch([db().prepare('UPDATE entries SET category = ? WHERE category = ? AND owner = ?').bind('',id,owner),db().prepare('DELETE FROM categories WHERE id = ? AND owner = ?').bind(id,owner)]);else await db().prepare('DELETE FROM entries WHERE id = ? AND owner = ?').bind(id,owner).run();return Response.json({ok:true});});}